services:
  - type: web
    name: game-server
    env: node
    plan: free
    buildCommand: |
      pnpm install
      pnpm --filter @game/shared build
      pnpm --filter @game/server build
    startCommand: pnpm --filter @game/server start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: game-server
          property: port
